#!/usr/bin/env bash
# Astrion testnet simulation setup.
#
# Generates wallets test1-5, funds them via friendbot, mints test tokens
# (USDC + WBTC) to each wallet using the deployed test-token contracts,
# and resolves the XLM native SAC address.
#
# Prerequisite: run `make deploy-testnet && make init-testnet` first so
# TEST_USDC_ID and TEST_WBTC_ID exist in addresses.env.
#
# Outputs (tracked by git):
#   sim/wallets.env   — public keys for all wallets
#   sim/tokens.env    — token contract IDs + XLM SAC
#   sim/state.env     — simulation round counter
#
# Outputs (gitignored — NEVER COMMIT):
#   sim/wallets.secret.env — private keys
#
# Usage:
#   sim/setup.sh [network] [addresses_env]
#   make sim-setup

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$(dirname "$SCRIPT_DIR")"   # repo root

network="${1:-testnet}"
addresses_env="${2:-deployments/${network}/addresses.env}"
sim_dir="sim"

wallets_env="${sim_dir}/wallets.env"
wallets_secret="${sim_dir}/wallets.secret.env"
tokens_env="${sim_dir}/tokens.env"
state_env="${sim_dir}/state.env"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Astrion Simulation Setup                                   ║"
printf '║  Network: %-51s║\n' "$network"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ─── pre-flight ───────────────────────────────────────────────────────────────
if [[ ! -f "$addresses_env" ]]; then
  echo "error: ${addresses_env} not found"
  echo "  Run: make deploy-testnet && make init-testnet" >&2
  exit 1
fi

set -a; source "$addresses_env"; set +a

if [[ -z "${TEST_USDC_ID:-}" || -z "${TEST_WBTC_ID:-}" ]]; then
  echo "error: TEST_USDC_ID or TEST_WBTC_ID not set in ${addresses_env}"
  echo "  Test tokens are only deployed on testnet (not mainnet)." >&2
  exit 1
fi

# ─── helpers ──────────────────────────────────────────────────────────────────

fund_account() {
  local address="$1" alias="$2"
  printf '  Funding %-14s  %s\n' "$alias" "${address:0:10}…"
  if [[ "$network" == "testnet" || "$network" == "futurenet" ]]; then
    local attempts=0
    until curl -sf "https://friendbot.stellar.org?addr=${address}" -o /dev/null; do
      attempts=$((attempts+1))
      if (( attempts >= 3 )); then
        echo "    warning: friendbot failed for ${alias} after 3 attempts" >&2
        return 0
      fi
      sleep 2
    done
  else
    echo "    note: non-testnet — fund ${address} manually."
  fi
}

pubkey_of() { stellar keys address "$1" 2>/dev/null; }

ensure_identity() {
  local alias="$1"
  if stellar keys address "$alias" &>/dev/null; then
    printf '  %-14s already exists → %s\n' "$alias" "$(pubkey_of "$alias")"
  else
    stellar keys generate "$alias"
    printf '  %-14s generated   → %s\n' "$alias" "$(pubkey_of "$alias")"
  fi
}

# ─── 1. generate wallets ──────────────────────────────────────────────────────
echo "Step 1 — Generate wallets"
echo ""

WALLET_NAMES=("test1" "test2" "test3" "test4" "test5")
for w in "${WALLET_NAMES[@]}"; do
  ensure_identity "$w"
done
echo ""

# ─── 2. fund via friendbot ────────────────────────────────────────────────────
echo "Step 2 — Fund via friendbot"
echo ""

for w in "${WALLET_NAMES[@]}"; do
  fund_account "$(pubkey_of "$w")" "$w"
done
echo ""

# ─── 3. write wallets.env ─────────────────────────────────────────────────────
echo "Step 3 — Write wallets.env"
echo ""

{
  echo "# Generated by sim/setup.sh — public keys only (safe to commit)"
  echo "# Network: ${network}"
  echo "# Date:    $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  for w in "${WALLET_NAMES[@]}"; do
    var="${w^^}_ADDRESS"
    echo "${var}=$(pubkey_of "$w")"
  done
} > "$wallets_env"
echo "  Wrote ${wallets_env}"
echo ""

# ─── 4. write wallets.secret.env ─────────────────────────────────────────────
echo "Step 4 — Write wallets.secret.env (NEVER COMMIT)"
echo ""

{
  echo "# PRIVATE KEYS — DO NOT COMMIT — DO NOT SHARE"
  echo "# Network: ${network}"
  echo "# Date:    $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  for w in "${WALLET_NAMES[@]}"; do
    var="${w^^}_SECRET"
    secret="$(stellar keys show "$w" 2>/dev/null || echo 'UNAVAILABLE')"
    echo "${var}=${secret}"
  done
} > "$wallets_secret"
chmod 600 "$wallets_secret"
echo "  Wrote ${wallets_secret}  (mode 600)"
echo ""

# ─── 5. resolve XLM native SAC ───────────────────────────────────────────────
echo "Step 5 — Resolve XLM native SAC"
echo ""

XLM_SAC_ID=""
XLM_SAC_ID="$(
  stellar -q contract asset deploy \
    --asset   "native" \
    --network "$network" \
    --source  "test1" \
    2>/dev/null | tail -n 1 || true
)"
if [[ -z "$XLM_SAC_ID" ]]; then
  XLM_SAC_ID="native"
  echo "  XLM SAC: using 'native' token keyword"
else
  echo "  XLM SAC → ${XLM_SAC_ID}"
fi
echo ""

# ─── 6. write tokens.env ─────────────────────────────────────────────────────
echo "Step 6 — Write tokens.env"
echo ""

{
  echo "# Generated by sim/setup.sh — token contract IDs"
  echo "# Network: ${network}"
  echo "# Date:    $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "# Test-token contracts (deployed by ops/deploy-all.sh, testnet only)"
  echo "USDC_TOKEN_ID=${TEST_USDC_ID}"
  echo "WBTC_TOKEN_ID=${TEST_WBTC_ID}"
  echo "XLM_SAC_ID=${XLM_SAC_ID}"
  echo ""
  echo "USDC_DECIMALS=7"
  echo "WBTC_DECIMALS=7"
  echo "XLM_DECIMALS=7"
} > "$tokens_env"
echo "  Wrote ${tokens_env}"
echo ""

# ─── 7. mint USDC + WBTC to each test wallet ─────────────────────────────────
echo "Step 7 — Mint tokens to test wallets"
echo ""

# Load wallet addresses
set -a; source "$wallets_env"; set +a

# Mint amounts (7 decimal places):
#   10,000 USDC = 100_000_000_000
#   1 WBTC      =  10_000_000
USDC_MINT=100000000000
WBTC_MINT=10000000

# Mint admin = deployer key that was used to deploy the test tokens.
# If ownership was transferred in init-all.sh, that key must be passed via
# the MINT_SOURCE env var (default: "deployer").
MINT_SOURCE="${MINT_SOURCE:-deployer}"

for w in "${WALLET_NAMES[@]}"; do
  waddr_var="${w^^}_ADDRESS"
  waddr="${!waddr_var}"

  printf '  Minting to %-8s  (%s…)\n' "$w" "${waddr:0:10}"

  # USDC — test-token mint(account, amount)
  if stellar contract invoke \
       --id      "$TEST_USDC_ID" \
       --network "$network" \
       --source  "$MINT_SOURCE" \
       -- mint \
       --account "$waddr" \
       --amount  "$USDC_MINT" \
       &>/dev/null
  then
    echo "    USDC: 10,000 minted ✓"
  else
    echo "    USDC: mint failed (already funded, or wrong MINT_SOURCE)"
  fi

  # WBTC — test-token mint(account, amount)
  if stellar contract invoke \
       --id      "$TEST_WBTC_ID" \
       --network "$network" \
       --source  "$MINT_SOURCE" \
       -- mint \
       --account "$waddr" \
       --amount  "$WBTC_MINT" \
       &>/dev/null
  then
    echo "    WBTC: 1.0000000 minted ✓"
  else
    echo "    WBTC: mint failed (already funded, or wrong MINT_SOURCE)"
  fi
done
echo ""

# ─── 8. initialize state.env ─────────────────────────────────────────────────
if [[ ! -f "$state_env" ]]; then
  {
    echo "# Simulation round counter — updated by sim/run.sh"
    echo "SIM_ROUND=0"
    echo "SIM_NETWORK=${network}"
  } > "$state_env"
  echo "  Wrote ${state_env}"
  echo ""
fi

# ─── summary ─────────────────────────────────────────────────────────────────
echo "════════════════════════════════════════════════════════════════"
echo "Setup complete. Files written:"
echo "  ${wallets_env}        (commit)"
echo "  ${wallets_secret}  (NEVER commit — gitignored)"
echo "  ${tokens_env}         (commit)"
echo "  ${state_env}          (commit)"
echo ""
echo "Token contracts:"
printf '  USDC → %s\n' "$TEST_USDC_ID"
printf '  WBTC → %s\n' "$TEST_WBTC_ID"
printf '  XLM  → %s\n' "$XLM_SAC_ID"
echo ""
echo "Next: make sim-run"
echo ""
