#!/usr/bin/env bash
# Full Morpho-stack bring-up for Stellar testnet, deployed by `steins-testnet`.
#
# Deploys + initializes every singleton (oracle-adapter, rate-model, core-pool,
# liquidation-engine, market-factory, vault-factory, adapter-registry, mock
# oracle, test tokens), uploads the market + vault WASM hashes the factories
# instantiate from, then bootstraps a demo end-to-end environment:
#   - enable an IRM (rate-model) and an LLTV (70%) on the market factory
#   - create one isolated market: collateral WBTC / loan USDC
#   - create one USDC vault via the vault factory
#   - deploy + initialize a market-adapter bound to that vault
#
# Idempotency is intentionally NOT a goal here: this is a fresh-environment
# bring-up. It moves any existing deployments/testnet state aside first.
#
# Usage:
#   ops/deploy-morpho-testnet.sh
#   SOURCE=steins-testnet NETWORK=testnet ops/deploy-morpho-testnet.sh

set -euo pipefail

network="${NETWORK:-testnet}"
source_account="${SOURCE:-steins-testnet}"
wasm_dir="${WASM_DIR:-target/wasm32v1-none/release}"
deploy_dir="${DEPLOY_DIR:-deployments/${network}}"
addresses_file="${deploy_dir}/addresses.env"

export DEPLOY_DIR="$deploy_dir"
source ops/state.sh
state_require_jq || exit 1

command -v jq >/dev/null || { echo "error: jq required" >&2; exit 1; }

admin="$(stellar keys address "$source_account")"
[[ -n "$admin" ]] || { echo "error: cannot resolve address for key '$source_account'" >&2; exit 1; }

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Astrion Morpho stack → ${network}"
echo "║  Deployer/admin: ${source_account} (${admin})"
echo "╚══════════════════════════════════════════════════════════════╝"

# ─── risk param constants (WAD = 1e18) ───────────────────────────────────────
WAD=1000000000000000000
LLTV_70=700000000000000000          # 0.70
LIQ_BONUS=50000000000000000         # 0.05 (deprecated field, kept in range)
RESERVE_FACTOR=100000000000000000   # 0.10
BASE_RATE=10000000000000000         # 0.01
SLOPE1=40000000000000000            # 0.04
SLOPE2=750000000000000000           # 0.75
OPTIMAL_UTIL=800000000000000000     # 0.80
CLOSE_FACTOR=500000000000000000     # 0.50 (legacy liquidation-engine)
MAX_STALENESS=9999999

# ─── 0. build ─────────────────────────────────────────────────────────────────
echo ""; echo "── Building contracts ──"
stellar contract build

# ─── reset state for a fresh environment ──────────────────────────────────────
mkdir -p "$deploy_dir"
ts="$(date -u +%Y%m%d-%H%M%S)"
for f in "$(_state_file)" "$addresses_file"; do
  [[ -f "$f" ]] && mv "$f" "${f}.bak-${ts}" && echo "moved $f → ${f}.bak-${ts}"
done
state_init "$network" "$source_account"

{
  echo "# Generated by ops/deploy-morpho-testnet.sh"
  echo "# Network:  ${network}"
  echo "# Deployer: ${source_account} (${admin})"
  echo "# Date:     $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Commit:   $(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
} > "$addresses_file"

# ─── helpers ──────────────────────────────────────────────────────────────────
wasm_path() {
  local stem="$1"
  if [[ -f "${wasm_dir}/${stem}.optimized.wasm" ]]; then
    echo "${wasm_dir}/${stem}.optimized.wasm"
  else
    echo "${wasm_dir}/${stem}.wasm"
  fi
}

invoke() { stellar -q contract invoke --network "$network" --source "$source_account" "$@"; }

record() {  # alias var_name contract_id wasm_path status
  local alias="$1" var="$2" id="$3" wpath="$4" status="$5"
  state_set "$alias" "contract_id" "$id"
  state_set "$alias" "wasm_sha256" "$(sha256sum "$wpath" | awk '{print $1}')"
  state_set "$alias" "wasm_file"   "$(basename "$wpath")"
  state_set "$alias" "status"      "$status"
  state_set "$alias" "deployed_at" "$(_ts)"
  printf '%s=%q\n' "$var" "$id" >> "$addresses_file"
  # Log to stderr so the only stdout from deploy()/deploy_token() is the bare
  # contract id captured by command substitution.
  printf '  %-20s %s\n' "$alias" "$id" >&2
}

deploy() {  # alias wasm_stem var_name  → echoes id
  local alias="$1" stem="$2" var="$3"
  local wpath; wpath="$(wasm_path "$stem")"
  local id; id="$(stellar -q contract deploy --wasm "$wpath" --network "$network" --source "$source_account" | tail -n1)"
  [[ -n "$id" ]] || { echo "error: deploy failed for $alias" >&2; exit 1; }
  record "$alias" "$var" "$id" "$wpath" "deployed"
  echo "$id"
}

upload() {  # wasm_stem  → echoes wasm hash
  local stem="$1" wpath; wpath="$(wasm_path "$stem")"
  stellar -q contract upload --wasm "$wpath" --network "$network" --source "$source_account" | tail -n1
}

# ─── 1. deploy singletons ─────────────────────────────────────────────────────
echo ""; echo "── Deploying contracts ──"
ORACLE_ADAPTER_ID="$(deploy oracle-adapter      oracle_adapter      ORACLE_ADAPTER_ID)"
RATE_MODEL_ID="$(deploy      rate-model          interest_rate_model RATE_MODEL_ID)"
CORE_POOL_ID="$(deploy       core-pool           core_pool           CORE_POOL_ID)"
LIQUIDATION_ENGINE_ID="$(deploy liquidation-engine liquidation_engine LIQUIDATION_ENGINE_ID)"
MARKET_FACTORY_ID="$(deploy  market-factory      market_factory      MARKET_FACTORY_ID)"
VAULT_FACTORY_ID="$(deploy   vault-factory       vault_factory       VAULT_FACTORY_ID)"
ADAPTER_REGISTRY_ID="$(deploy adapter-registry   adapter_registry    ADAPTER_REGISTRY_ID)"
MOCK_ORACLE_ID="$(deploy     mock-oracle         mock_oracle         MOCK_ORACLE_ID)"

# test tokens (constructor: admin, decimals, name, symbol)
deploy_token() {  # alias var symbol name
  local alias="$1" var="$2" symbol="$3" name="$4"
  local wpath; wpath="$(wasm_path test_token)"
  local id; id="$(stellar -q contract deploy --wasm "$wpath" --network "$network" --source "$source_account" \
    -- --admin "$admin" --decimals 7 --name "$name" --symbol "$symbol" | tail -n1)"
  [[ -n "$id" ]] || { echo "error: token deploy failed for $alias" >&2; exit 1; }
  record "$alias" "$var" "$id" "$wpath" "initialized"
  echo "$id"
}
TEST_USDC_ID="$(deploy_token test-usdc TEST_USDC_ID USDC "Test USD Coin")"
TEST_WBTC_ID="$(deploy_token test-wbtc TEST_WBTC_ID WBTC "Test Wrapped Bitcoin")"

# ─── 2. upload factory template WASM hashes ───────────────────────────────────
echo ""; echo "── Uploading factory template WASM ──"
MARKET_WASM_HASH="$(upload market)"
VAULT_WASM_HASH="$(upload vault)"
echo "  market wasm hash: $MARKET_WASM_HASH"
echo "  vault  wasm hash: $VAULT_WASM_HASH"
state_set "market-factory" "market_wasm_hash" "$MARKET_WASM_HASH"
state_set "vault-factory"  "vault_wasm_hash"  "$VAULT_WASM_HASH"

# ─── 3. initialize singletons ─────────────────────────────────────────────────
echo ""; echo "── Initializing ──"

invoke --id "$MOCK_ORACLE_ID" -- initialize --admin "$admin"
state_set mock-oracle status initialized; echo "  mock-oracle initialized"

invoke --id "$ORACLE_ADAPTER_ID" -- initialize \
  --admin "$admin" --default_oracle "$MOCK_ORACLE_ID" --default_max_staleness "$MAX_STALENESS"
state_set oracle-adapter status initialized; echo "  oracle-adapter initialized"

invoke --id "$RATE_MODEL_ID" -- initialize --admin "$admin" \
  --config "{\"base_rate\":\"${BASE_RATE}\",\"slope1\":\"${SLOPE1}\",\"slope2\":\"${SLOPE2}\",\"optimal_utilization\":\"${OPTIMAL_UTIL}\",\"reserve_factor\":\"${RESERVE_FACTOR}\"}"
state_set rate-model status initialized; echo "  rate-model initialized"

invoke --id "$CORE_POOL_ID" -- initialize \
  --admin "$admin" --oracle_adapter "$ORACLE_ADAPTER_ID" --rate_model "$RATE_MODEL_ID" --treasury "$admin"
state_set core-pool status initialized; echo "  core-pool initialized"

invoke --id "$LIQUIDATION_ENGINE_ID" -- initialize \
  --admin "$admin" --core_pool "$CORE_POOL_ID" --oracle_adapter "$ORACLE_ADAPTER_ID" --close_factor "$CLOSE_FACTOR"
state_set liquidation-engine status initialized; echo "  liquidation-engine initialized"

invoke --id "$MARKET_FACTORY_ID" -- initialize --admin "$admin" --market_wasm_hash "$MARKET_WASM_HASH"
state_set market-factory status initialized; echo "  market-factory initialized"

invoke --id "$VAULT_FACTORY_ID" -- initialize --owner "$admin" --vault_wasm_hash "$VAULT_WASM_HASH"
state_set vault-factory status initialized; echo "  vault-factory initialized"

invoke --id "$ADAPTER_REGISTRY_ID" -- initialize --owner "$admin"
state_set adapter-registry status initialized; echo "  adapter-registry initialized"

# ─── 4. oracle prices + wiring ────────────────────────────────────────────────
echo ""; echo "── Oracle prices + wiring ──"
invoke --id "$MOCK_ORACLE_ID" -- set_price --asset "{\"Stellar\":\"${TEST_USDC_ID}\"}" --price 10000000      # $1.00
invoke --id "$MOCK_ORACLE_ID" -- set_price --asset "{\"Stellar\":\"${TEST_WBTC_ID}\"}" --price 600000000000  # $60,000
invoke --id "$ORACLE_ADAPTER_ID" -- set_asset_oracle --asset "{\"Stellar\":\"${TEST_USDC_ID}\"}" --oracle "$MOCK_ORACLE_ID" --max_staleness "$MAX_STALENESS"
invoke --id "$ORACLE_ADAPTER_ID" -- set_asset_oracle --asset "{\"Stellar\":\"${TEST_WBTC_ID}\"}" --oracle "$MOCK_ORACLE_ID" --max_staleness "$MAX_STALENESS"
echo "  USDC=\$1.00  WBTC=\$60,000  wired to mock-oracle"

# ─── 5. enable IRM + LLTV, create demo isolated market ────────────────────────
echo ""; echo "── Demo isolated market (collateral WBTC / loan USDC, LLTV 70%) ──"
invoke --id "$MARKET_FACTORY_ID" -- enable_irm  --rate_model "$RATE_MODEL_ID"
invoke --id "$MARKET_FACTORY_ID" -- enable_lltv --lltv "$LLTV_70"

market_cfg="{\"collateral_asset\":\"${TEST_WBTC_ID}\",\"loan_asset\":\"${TEST_USDC_ID}\",\"oracle_adapter\":\"${ORACLE_ADAPTER_ID}\",\"lltv\":\"${LLTV_70}\",\"liquidation_bonus\":\"${LIQ_BONUS}\",\"reserve_factor\":\"${RESERVE_FACTOR}\",\"supply_cap\":\"0\",\"borrow_cap\":\"0\",\"rate_model\":\"${RATE_MODEL_ID}\",\"treasury\":\"${admin}\"}"
DEMO_MARKET_ID="$(invoke --id "$MARKET_FACTORY_ID" -- create_market --config "$market_cfg" | tr -d '"' | tail -n1)"
echo "  demo market: $DEMO_MARKET_ID"
printf 'DEMO_MARKET_ID=%q\n' "$DEMO_MARKET_ID" >> "$addresses_file"
state_set demo-market contract_id "$DEMO_MARKET_ID"
state_set demo-market status initialized

# ─── 6. create demo USDC vault ────────────────────────────────────────────────
echo ""; echo "── Demo USDC vault ──"
VAULT_SALT="$(printf '%s' 'astrion-usdc-vault-v1' | sha256sum | awk '{print $1}')"
DEMO_VAULT_ID="$(invoke --id "$VAULT_FACTORY_ID" -- create_vault \
  --owner "$admin" --asset "$TEST_USDC_ID" --salt "$VAULT_SALT" \
  --name "Astrion USDC Vault" --symbol "aUSDC" | tr -d '"' | tail -n1)"
echo "  demo vault: $DEMO_VAULT_ID"
printf 'DEMO_VAULT_ID=%q\n' "$DEMO_VAULT_ID" >> "$addresses_file"
state_set demo-vault contract_id "$DEMO_VAULT_ID"
state_set demo-vault status initialized

# ─── 7. deploy + init market-adapter for the demo vault ───────────────────────
echo ""; echo "── Market adapter (vault → market bridge) ──"
MARKET_ADAPTER_ID="$(deploy market-adapter market_adapter MARKET_ADAPTER_ID)"
invoke --id "$MARKET_ADAPTER_ID" -- initialize \
  --parent_vault "$DEMO_VAULT_ID" --asset "$TEST_USDC_ID" --market_factory "$MARKET_FACTORY_ID"
state_set market-adapter status initialized
echo "  market-adapter initialized → vault ${DEMO_VAULT_ID:0:8}…"

# ─── done ──────────────────────────────────────────────────────────────────────
echo ""; echo "Wrote ${addresses_file}"
state_print
echo "Done. Demo: vault ${DEMO_VAULT_ID:0:8}… / market ${DEMO_MARKET_ID:0:8}… / adapter ${MARKET_ADAPTER_ID:0:8}…"
